// Generated by CoffeeScript 1.6.3
(function() {
  var domWrapper, tag, tags, _i, _len,
    __slice = [].slice;

  tags = require('./tags');

  domWrapper = function(tag) {
    return function() {
      var attributes, contents;
      attributes = arguments[0], contents = 2 <= arguments.length ? __slice.call(arguments, 1) : [];
      if (typeof attributes === 'object' && !React.isValidComponent(attributes)) {
        return React.DOM[tag](attributes, contents);
      } else {
        return React.DOM[tag]({}, attributes, contents);
      }
    };
  };

  for (_i = 0, _len = tags.length; _i < _len; _i++) {
    tag = tags[_i];
    module.exports["_" + tag] = domWrapper(tag);
  }

}).call(this);
