// Generated by CoffeeScript 1.6.3
(function() {
  var normalizeComponentCalls, potentialTags, tags, tagsToImport,
    __indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; };

  tags = require('./tags');

  normalizeComponentCalls = function(source) {
    var normalize;
    normalize = function(source) {
      return source.replace(/((?:^|\n)(\s*)_\w+)(\s*\n\2[^\S\n]+)/g, '$1 {},$3');
    };
    return normalize(normalize(source));
  };

  potentialTags = function(source) {
    return source.match(/_\w+/g);
  };

  tagsToImport = function(source) {
    return (potentialTags(source)).filter(function(tag) {
      var _ref;
      return _ref = tag.slice(1), __indexOf.call(tags, _ref) >= 0;
    });
  };

  module.exports = function(source) {
    var normalizedSource;
    tags = tagsToImport(source);
    normalizedSource = normalizeComponentCalls(source);
    return "{" + (tags.join(', ')) + "} = hyper = require 'hyper'; " + normalizedSource;
  };

}).call(this);
